-- Create the prediction_logs table to track ALL AI usage (anonymous or logged in)
create table public.prediction_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  species_prediction text,
  confidence float,
  family text,
  class_name text,
  filename text,
  is_logged_in boolean default false,
  user_id uuid references auth.users(id), -- Optional, valid only if user is logged in
  ip_address text, -- Optional, if you want to track origin (requires extra backend work)
  execution_time_ms int -- How long the inference took
);

-- Enable Row Level Security (RLS)
alter table public.prediction_logs enable row level security;

-- POLICY 1: API (Service Role) can INSERT rows
-- (The backend uses the service role or generic key to insert)
create policy "Enable insert for authenticated and anon users"
on public.prediction_logs
for insert
with check (true);

-- POLICY 2: Admins/Devs can SELECT (View) rows
-- For now, we'll allow public read access for your Admin Dashboard if you aren't using strict Auth yet.
-- Ideally, you'd restrict this to a specific role.
create policy "Enable read access for all"
on public.prediction_logs
for select
using (true);
